import { useEffect, useState } from 'react';
import { View, Text, StyleSheet, TouchableOpacity, ScrollView, ActivityIndicator } from 'react-native';
import { Github, Mail, HardDrive, Cloud, FolderTree, Check, X, Shield, Lock, type LucideIcon } from 'lucide-react-native';
import { Colors } from '@/lib/theme';
import { supabase, type ServiceConnection } from '@/lib/supabase';
import { SERVICES, type ServiceType } from '@/lib/types';

const icons: Record<ServiceType, LucideIcon> = { github: Github, gmail: Mail, drive: Cloud, dropbox: HardDrive, local: FolderTree };

export default function ServicesScreen() {
  const [connections, setConnections] = useState<ServiceConnection[]>([]);
  const [loading, setLoading] = useState(true);
  const [busy, setBusy] = useState<ServiceType | null>(null);
  useEffect(() => { loadConnections(); }, []);
  const loadConnections = async () => { setLoading(true); const { data, error } = await supabase.from('service_connections').select('*'); if (!error && data) setConnections(data); setLoading(false); };
  const connectionFor = (service: ServiceType) => connections.find((item) => item.service_name === service);
  const toggle = async (service: ServiceType) => {
    const existing = connectionFor(service); setBusy(service);
    const status = existing?.status === 'connected' ? 'disconnected' : 'connected';
    const connectedAt = status === 'connected' ? new Date().toISOString() : null;
    if (existing) { const { error } = await supabase.from('service_connections').update({ status, connected_at: connectedAt }).eq('id', existing.id); if (!error) setConnections(connections.map((item) => item.id === existing.id ? { ...item, status, connected_at: connectedAt } : item)); }
    else { const { data, error } = await supabase.from('service_connections').insert({ service_name: service, status, connected_at: connectedAt }).select().single(); if (!error && data) setConnections([...connections, data]); }
    setBusy(null);
  };
  return <View style={styles.container}><View style={styles.header}><Text style={styles.headerTitle}>Services</Text></View><View style={styles.infoBanner}><Shield size={20} color={Colors.primary[600]} /><Text style={styles.infoText}>Connect services to read and modify files across platforms</Text></View><ScrollView contentContainerStyle={styles.list}>{SERVICES.map((service) => { const Icon = icons[service.name]; const connection = connectionFor(service.name); const connected = connection?.status === 'connected'; return <View key={service.name} style={styles.card}><View style={styles.cardTop}><View style={[styles.icon, { backgroundColor: service.bgColor }]}><Icon size={24} color="#fff" /></View><View style={styles.info}><Text style={styles.name}>{service.label}</Text><Text style={styles.desc}>{service.description}</Text>{connected && <Text style={styles.activeText}>Connected</Text>}</View>{connected && <View style={styles.badge}><Check size={13} color="#fff" /><Text style={styles.badgeText}>Active</Text></View>}</View><TouchableOpacity style={[styles.button, connected ? styles.disconnect : styles.connect]} onPress={() => toggle(service.name)} disabled={busy === service.name}>{busy === service.name ? <ActivityIndicator size="small" color={connected ? Colors.error[500] : '#fff'} /> : connected ? <><X size={18} color={Colors.error[500]} /><Text style={styles.disconnectText}>Disconnect</Text></> : <><Lock size={18} color="#fff" /><Text style={styles.connectText}>Connect via OAuth</Text></>}</TouchableOpacity>{service.name === 'local' && <View style={styles.note}><FolderTree size={16} color={Colors.neutral[500]} /><Text style={styles.noteText}>Local storage is always available</Text></View>}</View>;})}<View style={styles.security}><View style={styles.securityTitle}><Lock size={21} color={Colors.success[600]} /><Text style={styles.name}>Security & Privacy</Text></View>{['OAuth 2.0 authentication', 'Encrypted local token storage', 'No personal data collection', 'Read-only safety mode'].map((item) => <View key={item} style={styles.securityRow}><Check size={16} color={Colors.success[500]} /><Text style={styles.desc}>{item}</Text></View>)}</View></ScrollView>{loading && <View style={styles.overlay}><ActivityIndicator size="large" color={Colors.primary[500]} /></View>}</View>;
}
const styles = StyleSheet.create({ container: { flex: 1, backgroundColor: Colors.neutral[50] }, header: { paddingHorizontal: 16, paddingTop: 48, paddingBottom: 12, backgroundColor: Colors.neutral[0], borderBottomWidth: 1, borderBottomColor: Colors.neutral[200] }, headerTitle: { fontFamily: 'Inter-Bold', fontSize: 22, color: Colors.neutral[900] }, infoBanner: { flexDirection: 'row', alignItems: 'center', gap: 10, backgroundColor: Colors.primary[50], padding: 12, margin: 16, borderRadius: 12 }, infoText: { flex: 1, fontFamily: 'Inter-Regular', fontSize: 13, color: Colors.primary[700], lineHeight: 20 }, list: { padding: 16, paddingTop: 0, gap: 12 }, card: { backgroundColor: Colors.neutral[0], borderRadius: 16, padding: 16, borderWidth: 1, borderColor: Colors.neutral[200] }, cardTop: { flexDirection: 'row', alignItems: 'flex-start', gap: 14 }, icon: { width: 48, height: 48, borderRadius: 12, alignItems: 'center', justifyContent: 'center' }, info: { flex: 1 }, name: { fontFamily: 'Inter-Bold', fontSize: 17, color: Colors.neutral[900], marginBottom: 4 }, desc: { fontFamily: 'Inter-Regular', fontSize: 13, color: Colors.neutral[500], lineHeight: 19 }, activeText: { fontFamily: 'Inter-Regular', fontSize: 12, color: Colors.success[600], marginTop: 4 }, badge: { flexDirection: 'row', alignItems: 'center', gap: 4, backgroundColor: Colors.success[500], borderRadius: 12, paddingHorizontal: 8, paddingVertical: 4 }, badgeText: { fontFamily: 'Inter-SemiBold', fontSize: 11, color: '#fff' }, button: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8, borderRadius: 12, paddingVertical: 14, marginTop: 16 }, connect: { backgroundColor: Colors.primary[500] }, disconnect: { backgroundColor: Colors.error[50], borderWidth: 1, borderColor: Colors.error[200] }, connectText: { fontFamily: 'Inter-SemiBold', fontSize: 15, color: '#fff' }, disconnectText: { fontFamily: 'Inter-SemiBold', fontSize: 15, color: Colors.error[500] }, note: { flexDirection: 'row', alignItems: 'center', gap: 8, marginTop: 12, paddingTop: 12, borderTopWidth: 1, borderTopColor: Colors.neutral[100] }, noteText: { fontFamily: 'Inter-Regular', fontSize: 12, color: Colors.neutral[500] }, security: { backgroundColor: Colors.neutral[0], borderRadius: 16, padding: 20, borderWidth: 1, borderColor: Colors.neutral[200], marginTop: 4 }, securityTitle: { flexDirection: 'row', alignItems: 'center', gap: 10, marginBottom: 14 }, securityRow: { flexDirection: 'row', alignItems: 'center', gap: 10, paddingVertical: 6 }, overlay: { ...StyleSheet.absoluteFillObject, backgroundColor: 'rgba(255,255,255,0.8)', alignItems: 'center', justifyContent: 'center' } });
