import { useState } from 'react';
import { View, Text, StyleSheet, TouchableOpacity, ScrollView, Switch, Alert } from 'react-native';
import { Moon, Sun, Cpu, Zap, ZapOff, Code2, FileText, Shield, Info, Github, Trash2, ChevronRight, type LucideIcon } from 'lucide-react-native';
import { Colors } from '@/lib/theme';
import { supabase } from '@/lib/supabase';

type RowProps = { icon: LucideIcon; iconColor: string; iconBg: string; label: string; description: string; value?: boolean; onToggle?: (value: boolean) => void; onPress?: () => void };
export default function SettingsScreen() {
  const [darkMode, setDarkMode] = useState(false); const [offlineMode, setOfflineMode] = useState(true); const [cloudModels, setCloudModels] = useState(false); const [autoSave, setAutoSave] = useState(true); const [confirmDestructive, setConfirmDestructive] = useState(true);
  const clearData = () => Alert.alert('Clear All Data', 'Delete all chats, messages, and files?', [{ text: 'Cancel', style: 'cancel' }, { text: 'Delete Everything', style: 'destructive', onPress: async () => { await supabase.from('chat_messages').delete().neq('id', '00000000-0000-0000-0000-000000000000'); await supabase.from('chat_sessions').delete().neq('id', '00000000-0000-0000-0000-000000000000'); await supabase.from('files').delete().neq('id', '00000000-0000-0000-0000-000000000000'); Alert.alert('Done', 'All data has been cleared.'); } }]);
  const Row = ({ icon: Icon, iconColor, iconBg, label, description, value, onToggle, onPress }: RowProps) => <TouchableOpacity style={styles.row} onPress={onPress} disabled={!onPress}><View style={[styles.rowIcon, { backgroundColor: iconBg }]}><Icon size={20} color={iconColor} /></View><View style={styles.rowInfo}><Text style={styles.label}>{label}</Text><Text style={styles.description}>{description}</Text></View>{onToggle ? <Switch value={value} onValueChange={onToggle} trackColor={{ false: Colors.neutral[300], true: Colors.primary[500] }} thumbColor="#fff" /> : <ChevronRight size={20} color={Colors.neutral[400]} />}</TouchableOpacity>;
  return <ScrollView style={styles.container} contentContainerStyle={styles.content}><View style={styles.header}><Text style={styles.headerTitle}>Settings</Text></View><Section title="AI Engine"><Row icon={Cpu} iconColor={Colors.primary[600]} iconBg={Colors.primary[50]} label="Local Models" description="Run AI models offline" value={offlineMode} onToggle={setOfflineMode} /><Divider /><Row icon={cloudModels ? Zap : ZapOff} iconColor={Colors.accent[600]} iconBg={Colors.accent[50]} label="Cloud Models" description="Use cloud providers with an API key" value={cloudModels} onToggle={setCloudModels} /></Section><Section title="Appearance"><Row icon={darkMode ? Moon : Sun} iconColor={Colors.accent[600]} iconBg={Colors.accent[50]} label="Dark Mode" description="Optimized for coding sessions" value={darkMode} onToggle={setDarkMode} /><Divider /><Row icon={Code2} iconColor={Colors.secondary[600]} iconBg={Colors.secondary[50]} label="Syntax Highlighting" description="Color-code syntax in the editor" value={true} onToggle={() => {}} /></Section><Section title="Editor"><Row icon={FileText} iconColor={Colors.primary[600]} iconBg={Colors.primary[50]} label="Auto-save" description="Save changes automatically" value={autoSave} onToggle={setAutoSave} /><Divider /><Row icon={Shield} iconColor={Colors.warning[600]} iconBg={Colors.warning[50]} label="Confirm Destructive Actions" description="Two-step confirmation for deletes" value={confirmDestructive} onToggle={setConfirmDestructive} /></Section><Section title="About"><Row icon={Info} iconColor={Colors.primary[600]} iconBg={Colors.primary[50]} label="About App" description="Version 1.0.0 - AI Coding Assistant" onPress={() => Alert.alert('AI Coding Assistant', 'An AI-powered coding assistant for generating and managing code.')} /><Divider /><Row icon={Github} iconColor="#fff" iconBg="#24292f" label="Open Source" description="MIT licensed" onPress={() => Alert.alert('Open Source', 'This app is open-source under the MIT license.')} /></Section><Section title="Data"><Row icon={Trash2} iconColor={Colors.error[500]} iconBg={Colors.error[50]} label="Clear All Data" description="Delete all chats, messages, and files" onPress={clearData} /></Section><Text style={styles.version}>AI Coding Assistant v1.0.0</Text></ScrollView>;
}
function Section({ title, children }: { title: string; children: React.ReactNode }) { return <View style={styles.section}><Text style={styles.sectionTitle}>{title}</Text><View style={styles.card}>{children}</View></View>; }
function Divider() { return <View style={styles.divider} />; }
const styles = StyleSheet.create({ container: { flex: 1, backgroundColor: Colors.neutral[50] }, content: { paddingBottom: 40 }, header: { paddingHorizontal: 16, paddingTop: 48, paddingBottom: 12, backgroundColor: Colors.neutral[0], borderBottomWidth: 1, borderBottomColor: Colors.neutral[200] }, headerTitle: { fontFamily: 'Inter-Bold', fontSize: 22, color: Colors.neutral[900] }, section: { marginTop: 24, paddingHorizontal: 16 }, sectionTitle: { fontFamily: 'Inter-SemiBold', fontSize: 13, color: Colors.neutral[500], marginBottom: 10, marginLeft: 4, textTransform: 'uppercase', letterSpacing: 0.5 }, card: { backgroundColor: Colors.neutral[0], borderRadius: 14, borderWidth: 1, borderColor: Colors.neutral[200], overflow: 'hidden' }, row: { flexDirection: 'row', alignItems: 'center', padding: 14, gap: 12 }, rowIcon: { width: 40, height: 40, borderRadius: 10, alignItems: 'center', justifyContent: 'center' }, rowInfo: { flex: 1 }, label: { fontFamily: 'Inter-SemiBold', fontSize: 15, color: Colors.neutral[900], marginBottom: 2 }, description: { fontFamily: 'Inter-Regular', fontSize: 13, color: Colors.neutral[500], lineHeight: 18 }, divider: { height: 1, backgroundColor: Colors.neutral[100], marginLeft: 66 }, version: { textAlign: 'center', fontFamily: 'Inter-Regular', fontSize: 12, color: Colors.neutral[400], marginTop: 24 } });
