CREATE TABLE IF NOT EXISTS chat_sessions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), title text NOT NULL, created_at timestamptz DEFAULT now(), updated_at timestamptz DEFAULT now());
ALTER TABLE chat_sessions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "anon_select_chat_sessions" ON chat_sessions FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "anon_insert_chat_sessions" ON chat_sessions FOR INSERT TO anon, authenticated WITH CHECK (true);
CREATE POLICY "anon_update_chat_sessions" ON chat_sessions FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);
CREATE POLICY "anon_delete_chat_sessions" ON chat_sessions FOR DELETE TO anon, authenticated USING (true);
CREATE TABLE IF NOT EXISTS chat_messages (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), session_id uuid NOT NULL REFERENCES chat_sessions(id) ON DELETE CASCADE, role text NOT NULL CHECK (role IN ('user', 'assistant')), content text NOT NULL, language text, is_code boolean NOT NULL DEFAULT false, created_at timestamptz DEFAULT now());
ALTER TABLE chat_messages ENABLE ROW LEVEL SECURITY;
CREATE POLICY "anon_select_chat_messages" ON chat_messages FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "anon_insert_chat_messages" ON chat_messages FOR INSERT TO anon, authenticated WITH CHECK (true);
CREATE POLICY "anon_update_chat_messages" ON chat_messages FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);
CREATE POLICY "anon_delete_chat_messages" ON chat_messages FOR DELETE TO anon, authenticated USING (true);
CREATE TABLE IF NOT EXISTS files (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name text NOT NULL, path text NOT NULL, language text, content text NOT NULL DEFAULT '', service text NOT NULL CHECK (service IN ('github', 'gmail', 'drive', 'dropbox', 'local')), size integer NOT NULL DEFAULT 0, created_at timestamptz DEFAULT now(), updated_at timestamptz DEFAULT now());
ALTER TABLE files ENABLE ROW LEVEL SECURITY;
CREATE POLICY "anon_select_files" ON files FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "anon_insert_files" ON files FOR INSERT TO anon, authenticated WITH CHECK (true);
CREATE POLICY "anon_update_files" ON files FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);
CREATE POLICY "anon_delete_files" ON files FOR DELETE TO anon, authenticated USING (true);
CREATE TABLE IF NOT EXISTS service_connections (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), service_name text NOT NULL UNIQUE CHECK (service_name IN ('github', 'gmail', 'drive', 'dropbox', 'local')), status text NOT NULL DEFAULT 'disconnected' CHECK (status IN ('connected', 'disconnected')), connected_at timestamptz, metadata jsonb NOT NULL DEFAULT '{}'::jsonb);
ALTER TABLE service_connections ENABLE ROW LEVEL SECURITY;
CREATE POLICY "anon_select_service_connections" ON service_connections FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "anon_insert_service_connections" ON service_connections FOR INSERT TO anon, authenticated WITH CHECK (true);
CREATE POLICY "anon_update_service_connections" ON service_connections FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);
CREATE POLICY "anon_delete_service_connections" ON service_connections FOR DELETE TO anon, authenticated USING (true);
CREATE INDEX IF NOT EXISTS idx_chat_messages_session_id ON chat_messages(session_id);
CREATE INDEX IF NOT EXISTS idx_files_service ON files(service);
